// Copyright 2022 Google LLC.
// SPDX-License-Identifier: Apache-2.0
`default_nettype none

// tiny_user_project top module instance
// generated by configure.py
module tiny_user_project(
`ifdef USE_POWER_PINS
    inout vccd1,
    inout vssd1,
`endif
    // IOs
    input  [`MPRJ_IO_PADS-1:0] io_in,
    output [`MPRJ_IO_PADS-1:0] io_out,
    output [`MPRJ_IO_PADS-1:0] io_oeb,
);

// pass input and output pins defined in user_defines.v
M_main mod (
    .clock(io_in[0]),
    .reset(io_in[1]),
    .in_io_in(io_in[17:8]),
    .out_io_out(io_out[25:18])
);
// all output enabled
assign io_oeb[25:18] = 8'b0;

endmodule	// tiny_user_project

`default_nettype wire